import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={` ${poppins.variable}  h-full antialiased`}
    >
      <body className={` ${poppins.variable} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
